server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway: #网管路由配置
      routes:
        - id: bill_service #路由id 自定义，只要唯一即可
         #uri: http://127.0.0.1:8081 #路由器的目标地址 http是固定地址
          uri: lb://billService #路由的目标地址 lb就是负载均衡loadBalance，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=//billuser/** #这个是按照路径匹配，只要以/user/开头就符合要求
        - id: user_service #路由id 自定义，只要唯一即可
          #uri: http://127.0.0.1:8081 #路由器的目标地址 http是固定地址
          uri: lb://userService #路由的目标地址 lb就是负载均衡loadBalance，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=//user/** #这个是按照路径匹配，只要以/user/开头就符合要求