server:
  port: 8082
spring:
  application:
    name: billService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cloudexample
    username: root
    password: q12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
debug: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka #eureka的地址信息
