server:
  port: 8082
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#      discovery:
#        cluster-name: G1 #集群信息
#        namespace: e095a5f7-4672-4c1d-9ff1-f233784e498c #命名空间

  application:
    name: billService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cloudexample
    username: root
    password: q12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
debug: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10001/eureka #eureka的地址信息
