server:
  port: 8081
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#      discovery:
#        cluster-name: G1
  application:
    name: userService
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cloudexample
    username: root
    password: q12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
debug: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10001/eureka #eureka的地址信息

#feign:
#  client:
#    config:
#      default: #全局配置 对于所有微服务都生效

feign:
  client:
    config:
      billService: #对于某个微服务生效
        loggerLevel: BASIC
  httpclient:
    enabled: true
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 #每个路径的最大连接数